name: mfcc
version: 1.1.0
homepage: https://github.com/Lokhozt/mfcc
description: A library written in Dart to extract Mel-Frequency Cepstral Coefficients (MFCCs) from a signal.

environment:
  sdk: ^3.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.6.0
dependencies:
  fftea: ^1.5.0+1
